import type { AiManifestResponse } from '../../../shared/api-contracts.js';
import { AiManifestResponseSchema } from '../../../shared/api-contracts.js';
import { AI_MANIFEST_SCHEMA_VERSION } from './constants.js';

const STATIC: AiManifestResponse = {
  schemaVersion: AI_MANIFEST_SCHEMA_VERSION,
  description:
    '§2.0 AI slice manifest — HTTP paths and Zod export names from shared/api-contracts.ts. **Parameterized GETs**: use MCP tools in the optional **mcpTool** field (`get_ai_*`) — same payloads as GET /api/ai/* including query parity; legacy bankstatements://ai/* resources retain default-arg snapshots (see MCP server resource descriptions). Transaction drill (`GET /api/ai/transactions-drill` / MCP `query_transactions`): `account` is optional (all accounts); cross-account queries omit transfers by default unless `type`/`includeTransfers` apply.',
  slices: [
    {
      method: 'GET',
      path: '/api/ai/liquidity',
      queryParams: ['account', 'financialYear', 'groupByEntity'],
      responseSchemaExport: 'AiLiquidityResponseSchema',
      mcpTool: 'get_ai_liquidity',
    },
    {
      method: 'GET',
      path: '/api/ai/pipeline',
      queryParams: ['days', 'entityId'],
      responseSchemaExport: 'AiPipelineResponseSchema',
      mcpTool: 'get_ai_pipeline',
    },
    {
      method: 'GET',
      path: '/api/ai/runway',
      queryParams: ['days', 'entityId', 'detail'],
      responseSchemaExport: 'RunwayResponseSchema',
      mcpTool: 'get_ai_runway',
    },
    {
      method: 'GET',
      path: '/api/ai/snapshot',
      queryParams: [
        'days',
        'entityId',
        'detail',
        'account',
        'financialYear',
        'groupByEntity',
      ],
      responseSchemaExport: 'AiSnapshotResponseSchema',
      mcpTool: 'get_ai_snapshot',
    },
    {
      method: 'GET',
      path: '/api/ai/financial-snapshot',
      queryParams: [
        'days',
        'entityId',
        'detail',
        'account',
        'financialYear',
        'groupByEntity',
        'commitmentDays',
      ],
      responseSchemaExport: 'AiFinancialSnapshotResponseSchema',
      mcpTool: 'get_ai_financial_snapshot',
    },
    {
      method: 'GET',
      path: '/api/ai/financial-safety',
      queryParams: [
        'days',
        'entityId',
        'detail',
        'account',
        'financialYear',
        'groupByEntity',
        'commitmentDays',
      ],
      responseSchemaExport: 'AiFinancialSafetyResponseSchema',
      mcpTool: 'get_ai_financial_safety',
    },
    {
      method: 'GET',
      path: '/api/ai/net-worth-history',
      queryParams: [],
      responseSchemaExport: 'AiNetWorthHistoryResponseSchema',
    },
    {
      method: 'GET',
      path: '/api/ai/entity-liquidity-fx',
      queryParams: [],
      responseSchemaExport: 'AiEntityLiquidityFxResponseSchema',
    },
    {
      method: 'GET',
      path: '/api/ai/spend-by-currency',
      queryParams: ['calendarMonth', 'financialYear', 'entityId', 'account'],
      responseSchemaExport: 'AiSpendByCurrencyResponseSchema',
      mcpTool: 'get_ai_spend_by_currency',
    },
    {
      method: 'GET',
      path: '/api/ai/spend-rate',
      queryParams: ['window', 'entityId'],
      responseSchemaExport: 'AiSpendRateResponseSchema',
      mcpTool: 'analytics_get_spend_rate',
    },
    {
      method: 'GET',
      path: '/api/ai/available-funds',
      queryParams: ['days', 'entityId'],
      responseSchemaExport: 'AiAvailableFundsResponseSchema',
      mcpTool: 'analytics_get_available_funds',
    },
    {
      method: 'GET',
      path: '/api/ai/upcoming',
      queryParams: ['months', 'kind', 'entityId'],
      responseSchemaExport: 'AiUpcomingResponseSchema',
      mcpTool: 'analytics_get_upcoming',
    },
    {
      method: 'GET',
      path: '/api/ai/survival',
      queryParams: ['scope', 'dailyDiscretionary', 'targetDate', 'horizonDays'],
      responseSchemaExport: 'AiSurvivalResponseSchema',
      mcpTool: 'analytics_get_survival',
    },
    {
      method: 'GET',
      path: '/api/ai/spend-allowance',
      queryParams: ['period'],
      responseSchemaExport: 'AiSpendAllowanceResponseSchema',
      mcpTool: 'survival_get_allowance',
    },
    {
      method: 'GET',
      path: '/api/ai/manifest',
      queryParams: [],
      responseSchemaExport: 'AiManifestResponseSchema',
    },
    {
      method: 'GET',
      path: '/api/ai/warnings',
      queryParams: [],
      responseSchemaExport: 'EntityFoundationWarningsResponseSchema',
    },
    {
      method: 'GET',
      path: '/api/ai/income-composition',
      queryParams: [],
      responseSchemaExport: 'IncomeCompositionResponseSchema',
    },
    {
      method: 'GET',
      path: '/api/ai/debt-strategy',
      queryParams: [],
      responseSchemaExport: 'DebtStrategyStateResponseSchema',
    },
    {
      method: 'GET',
      path: '/api/ai/spend-context',
      queryParams: [],
      responseSchemaExport: 'AiSpendContextResponseSchema',
    },
    {
      method: 'GET',
      path: '/api/ai/transactions-drill',
      queryParams: [
        'financialYear',
        'year',
        'month',
        'dateFrom',
        'dateTo',
        'account',
        'type',
        'includeTransfers',
        'search',
        'merchantModalLabel',
        'limit',
        'includeRows',
      ],
      responseSchemaExport: 'AiTransactionDrillResponseSchema',
    },
    {
      method: 'GET',
      path: '/api/expenses/overview',
      queryParams: [],
      responseSchemaExport: 'ExpensesSheetResponseSchema',
    },
    {
      method: 'GET',
      path: '/api/expenses/recurring',
      queryParams: ['account', 'financialYear'],
      responseSchemaExport: 'RecurringExpensesResponseSchema',
    },
    {
      method: 'GET',
      path: '/api/expenses/ad-hoc',
      queryParams: ['account', 'financialYear', 'min', 'limit'],
      responseSchemaExport: 'AdHocExpensesResponseSchema',
    },
    {
      method: 'GET',
      path: '/api/contracts/expected-receipts',
      queryParams: ['days', 'entityId'],
      responseSchemaExport: 'ExpectedReceiptsResponseSchema',
    },
  ],
  contractSchemaExports: [
    'AccountBalanceSchema',
    'AdHocExpensesResponseSchema',
    'AiEntityLiquidityFxResponseSchema',
    'AiFinancialSafetyResponseSchema',
    'AiFinancialSnapshotResponseSchema',
    'AiLiquidityResponseSchema',
    'AiManifestResponseSchema',
    'AiNetWorthHistoryResponseSchema',
    'AiPipelineRowSchema',
    'AiPipelineResponseSchema',
    'AiSnapshotResponseSchema',
    'AiSpendByCurrencyPeriodSchema',
    'AiSpendByCurrencyResponseSchema',
    'AiSpendRateResponseSchema',
    'AiAvailableFundsResponseSchema',
    'AiUpcomingResponseSchema',
    'AiSurvivalResponseSchema',
    'AiSpendAllowanceResponseSchema',
    'AiSpendContextResponseSchema',
    'AiTransactionDrillQuerySchema',
    'AiTransactionDrillResponseSchema',
    'DebtStrategyStateResponseSchema',
    'EntityFoundationWarningsResponseSchema',
    'ExpectedReceiptRowSchema',
    'ExpectedReceiptsResponseSchema',
    'ExpensesSheetResponseSchema',
    'IncomeCompositionResponseSchema',
    'LiquidityCommitmentsOverviewSchema',
    'NetWorthSnapshotCaptureResponseSchema',
    'NetWorthSnapshotRowSchema',
    'ObligationRowSchema',
    'RecurringExpensesResponseSchema',
    'RunwayResponseSchema',
  ],
};

export function buildAiManifest(): AiManifestResponse {
  return AiManifestResponseSchema.parse(STATIC);
}

/** Stable JSON string for drift tests (no timestamps). */
export function aiManifestDriftFingerprint(): string {
  return JSON.stringify(STATIC);
}
