/**
 * Merchants domain — raw entry data.
 *
 * The ordered, flat list of merchant-recognition entries. Entries are
 * checked top-to-bottom at call time; the first matching entry wins
 * for both category and display-name resolution, so the declared order
 * here is semantically load-bearing.
 *
 * Person-derived entries (narrow payroll + generic transfer rows for
 * each configured person) are NOT listed here. They are prepended at
 * registry build time from the people domain so that we have a single
 * source of truth for "how do we recognise David/Heena" (see
 * `server/domain/people/data.ts`).
 *
 * IMPORTANT: Narrow **Payroll** (salary tokens, no dividend) sits
 * before generic person-name **Transfers**. Remaining **Transfers**
 * rows stay early so other inter-account movements match first.
 */

import type { MerchantEntry } from './schema.js';
import {
  REGEX_DRAW_DOWN,
  REGEX_MERCHANT_BARCLAYS_PREMIUM_LINE,
  REGEX_MERCHANT_TRANSFERWISE,
  REGEX_OPTIONAL_FT,
} from './transfer-pairing-seeds.js';

export const STATIC_MERCHANT_DATA: readonly MerchantEntry[] = [
  { pattern: /MONZO JOINT/i, category: 'Transfers', displayName: 'Monzo Joint' },
  // Payroll from own company — Income, not inter-account Transfers (must stay above generic transfer patterns)
  { pattern: /AUTONIZE|AUTONIZEITLIMITED/i, category: 'Transfers', displayName: 'Autonize IT' },
  { pattern: REGEX_MERCHANT_BARCLAYS_PREMIUM_LINE, category: 'Transfers', displayName: null },
  { pattern: REGEX_MERCHANT_TRANSFERWISE, category: 'Transfers', displayName: 'Wise (TransferWise)' },
  { pattern: REGEX_OPTIONAL_FT, category: 'Transfers', displayName: 'Internal Transfer' },
  { pattern: REGEX_DRAW_DOWN, category: 'Transfers', displayName: 'Credit line drawdown' },
  // EE (mobile / phone airtime): outgoing bills only — category Utilities; recurring pipeline counts them
  // as expenses (negative outflows), never on the income/recurring-rent path. Placed before generic
  // "VIA MOBILE" so DD copy like "EE LIMITED … VIA MOBILE" is not misclassified as Transfers.
  {
    pattern:
      /EE\s+(?:LIMITED|LTD)\b|EE\.CO\.UK|EE\s+ONLINE|EVERYTHING\s+EVERYWHERE|PAYMENT\s+TO\s+EE\b|T-?MOBILE\s*(?:\*|\s)*EE\b|\bBT\s+(?:GROUP|PLC|MOBILE|CONSUMER)\b.{0,48}\bEE\b|\bEE\b.{0,48}\bBT\s+(?:GROUP|PLC)\b/i,
    category: 'Utilities',
    displayName: 'EE',
  },
  { pattern: /VIA MOBILE/i, category: 'Transfers', displayName: 'Mobile Transfer' },
  { pattern: /ROYAL BANK \d{2}/i, category: 'Transfers', displayName: 'Royal Bank Transfer' },
  { pattern: /BMACH \d{2}/i, category: 'Transfers', displayName: 'BMACH Transfer' },
  { pattern: /SULEIMAN OMAR/i, category: 'Transfers', displayName: null },
  { pattern: /GENERAL REGISTER/i, category: 'Transfers', displayName: null },
  { pattern: /EMMA ALLEN/i, category: 'Transfers', displayName: null },
  { pattern: /THOMAS\s+HIGGINS/i, category: 'Transfers', displayName: null },
  { pattern: /GENEVIC/i, category: 'Transfers', displayName: null },
  { pattern: /ENRIQUEZ/i, category: 'Transfers', displayName: null },
  { pattern: /RISHI TAILOR/i, category: 'Transfers', displayName: null },

  // ─── Tax ────────────────────────────────────────────────────────────────────
  { pattern: /\bHMRC\b/i, category: 'Tax', displayName: 'HMRC' },
  { pattern: /TAX SAVINGS/i, category: 'Tax', displayName: 'Tax Savings' },
  { pattern: /CUMBERNAULD/i, category: 'Tax', displayName: 'HMRC Cumbernauld' },

  // ─── Housing ────────────────────────────────────────────────────────────────
  { pattern: /HALIFAX/i, category: 'Housing', displayName: 'Halifax Mortgage' },
  { pattern: /COVENTRY\s+B/i, category: 'Housing', displayName: 'Coventry Building Society' },
  // Card lines often end with NATWEST GBR; classify the merchant before the generic bank token.
  { pattern: /UBER\s*\*?\s*EATS?\b/i, category: 'Eating Out', displayName: 'Uber Eats' },
  { pattern: /UBER(?!\s*\*?\s*EAT)/i, category: 'Transport', displayName: 'Uber' },
  { pattern: /\bNATWEST\b/i, category: 'Housing', displayName: 'NatWest Mortgage' },
  { pattern: /MORTGAGE/i, category: 'Housing', displayName: null },
  { pattern: /HAVERING COUNCIL|LONDON BOROUGH|COUNCIL TAX/i, category: 'Housing', displayName: 'Council Tax' },

  // ─── Debt Repayment ─────────────────────────────────────────────────────────
  { pattern: /NOVUNA/i, category: 'Debt Repayment', displayName: 'Novuna Finance' },
  { pattern: /SANTANDER/i, category: 'Debt Repayment', displayName: 'Santander' },
  { pattern: /MBNA/i, category: 'Debt Repayment', displayName: 'MBNA' },
  { pattern: /FUNDING CIRCLE/i, category: 'Debt Repayment', displayName: 'Funding Circle' },
  { pattern: /BARCLAYS PARTNER/i, category: 'Debt Repayment', displayName: 'Barclays Partner Finance' },
  { pattern: /CAPITAL ON TAP/i, category: 'Debt Repayment', displayName: 'Capital on Tap' },
  { pattern: /WWW\.BARCLAYCARD|BCARD/i, category: 'Debt Repayment', displayName: 'Barclaycard' },
  { pattern: /BANK OF IRELAND/i, category: 'Debt Repayment', displayName: 'Bank of Ireland' },
  { pattern: /FORD CREDIT/i, category: 'Debt Repayment', displayName: 'Ford Credit' },
  { pattern: /CREDIT STYLE/i, category: 'Debt Repayment', displayName: 'Credit Style' },
  { pattern: /BARCLAYS\s+0520A/i, category: 'Debt Repayment', displayName: 'Bounce Back Loan' },
  { pattern: /BARCLAYS\s+\d{4}/i, category: 'Debt Repayment', displayName: null },
  { pattern: /INTEREST CHARGE\b(?!D)/i, category: 'Debt Repayment', displayName: 'Interest Charges' },
  { pattern: /BALANCE.*TRANSACTION/i, category: 'Debt Repayment', displayName: 'Balance Transaction' },

  // ─── Childcare & Education ──────────────────────────────────────────────────
  { pattern: /HEADSTART/i, category: 'Childcare & Education', displayName: 'Headstart' },
  { pattern: /MONTESSORI/i, category: 'Childcare & Education', displayName: 'Montessori' },
  { pattern: /EASTMINSTER/i, category: 'Childcare & Education', displayName: 'Eastminster School' },
  { pattern: /STAGES PERFORMER/i, category: 'Childcare & Education', displayName: 'Stagecoach Performing Arts' },
  { pattern: /LITTLE KICKER/i, category: 'Childcare & Education', displayName: 'Little Kickers' },
  { pattern: /SCHOOLHIRE|SCHOOL/i, category: 'Childcare & Education', displayName: null },
  { pattern: /KIDZ CAMP/i, category: 'Childcare & Education', displayName: 'Kidz Camp' },
  { pattern: /SCOOTY WOOTY/i, category: 'Childcare & Education', displayName: 'Scooty Wooty' },
  { pattern: /CHILDCARE GOV/i, category: 'Childcare & Education', displayName: 'Childcare (Gov)' },
  { pattern: /FUNTASTIC FOOTBALL/i, category: 'Childcare & Education', displayName: 'Funtastic Football' },
  { pattern: /CHECKMAT/i, category: 'Childcare & Education', displayName: 'Checkmat BJJ' },
  { pattern: /GIDEA PARK COACHING/i, category: 'Childcare & Education', displayName: 'Gidea Park Coaching' },

  // ─── Insurance ──────────────────────────────────────────────────────────────
  { pattern: /ORIENT\s+INSURANCE/i, category: 'Insurance', displayName: 'Orient Insurance PJSC' },
  { pattern: /CHURCHILL/i, category: 'Insurance', displayName: 'Churchill Insurance' },
  { pattern: /LIVERPOOL VICTORIA|\bLV\b/i, category: 'Insurance', displayName: 'LV Insurance' },
  { pattern: /AIG LIFE/i, category: 'Insurance', displayName: 'AIG Life' },
  { pattern: /\bAIG\b/i, category: 'Insurance', displayName: 'AIG' },
  { pattern: /D&G.*CARE|CARE PLAN|AO RETAIL/i, category: 'Insurance', displayName: 'Appliance Care Plan' },
  { pattern: /AVIVA/i, category: 'Insurance', displayName: 'Aviva' },
  { pattern: /AXA INSURANCE/i, category: 'Insurance', displayName: 'AXA Insurance' },
  { pattern: /DIRECT LINE/i, category: 'Insurance', displayName: 'Direct Line' },
  { pattern: /ADMIRAL/i, category: 'Insurance', displayName: 'Admiral' },
  { pattern: /KINGSBRIDGE/i, category: 'Insurance', displayName: 'Kingsbridge Insurance' },

  // ─── Utilities ──────────────────────────────────────────────────────────────
  { pattern: /SCOTTISH POWER/i, category: 'Utilities', displayName: 'Scottish Power' },
  { pattern: /OCTOPUS ENERGY/i, category: 'Utilities', displayName: 'Octopus Energy' },
  { pattern: /BRITISH GAS/i, category: 'Utilities', displayName: 'British Gas' },
  { pattern: /THAMES WATER/i, category: 'Utilities', displayName: 'Thames Water' },
  { pattern: /NORTHUMBRIAN WATER/i, category: 'Utilities', displayName: 'Northumbrian Water' },
  { pattern: /ANGLIAN WATER/i, category: 'Utilities', displayName: 'Anglian Water' },
  { pattern: /SOUTHERN WATER/i, category: 'Utilities', displayName: 'Southern Water' },
  { pattern: /SEVERN TRENT/i, category: 'Utilities', displayName: 'Severn Trent' },
  { pattern: /WATER PLUS/i, category: 'Utilities', displayName: 'Water Plus' },
  { pattern: /TONIK ENERGY/i, category: 'Utilities', displayName: 'Tonik Energy' },
  { pattern: /VIRGIN MEDIA/i, category: 'Utilities', displayName: 'Virgin Media' },
  { pattern: /TV LICEN/i, category: 'Utilities', displayName: 'TV Licence' },
  { pattern: /1PMOBILE/i, category: 'Utilities', displayName: '1pMobile' },
  { pattern: /RING BASIC PLAN/i, category: 'Utilities', displayName: 'Ring Security' },
  { pattern: /DU F09DB/i, category: 'Utilities', displayName: 'du (UAE)' },

  // ─── Groceries ──────────────────────────────────────────────────────────────
  { pattern: /TESCO/i, category: 'Groceries', displayName: 'Tesco' },
  { pattern: /ASDA/i, category: 'Groceries', displayName: 'Asda' },
  { pattern: /SAINSBURY/i, category: 'Groceries', displayName: "Sainsbury's" },
  { pattern: /LIDL/i, category: 'Groceries', displayName: 'Lidl' },
  { pattern: /ALDI/i, category: 'Groceries', displayName: 'Aldi' },
  { pattern: /MORRISONS/i, category: 'Groceries', displayName: 'Morrisons' },
  { pattern: /UNION COOP/i, category: 'Groceries', displayName: 'Union Coop' },
  { pattern: /CO[\s,-]?OP(?!.*BANK)/i, category: 'Groceries', displayName: 'Co-op' },
  { pattern: /COSTCO/i, category: 'Groceries', displayName: 'Costco' },
  { pattern: /WAITROSE/i, category: 'Groceries', displayName: 'Waitrose' },
  { pattern: /\bB&M\b/i, category: 'Groceries', displayName: 'B&M' },
  { pattern: /OCADO/i, category: 'Groceries', displayName: 'Ocado' },
  { pattern: /AMAZON FRESH/i, category: 'Groceries', displayName: 'Amazon Fresh' },
  { pattern: /M&S\b/i, category: 'Groceries', displayName: 'M&S' },
  { pattern: /ICELAND/i, category: 'Groceries', displayName: 'Iceland' },
  { pattern: /MODERN MILKMAN/i, category: 'Groceries', displayName: 'Modern Milkman' },
  { pattern: /\bLULU\b/i, category: 'Groceries', displayName: null },
  { pattern: /CARREFOUR/i, category: 'Groceries', displayName: 'Carrefour' },
  { pattern: /NEW W MART/i, category: 'Groceries', displayName: 'New W Mart' },
  { pattern: /HOO HING/i, category: 'Groceries', displayName: 'Hoo Hing' },
  { pattern: /BUDGENS/i, category: 'Groceries', displayName: 'Budgens' },
  { pattern: /OXLOW FOOD|OXLANE FOOD/i, category: 'Groceries', displayName: 'Oxlow Food Centre' },
  { pattern: /STATION ROAD CONVENIEN/i, category: 'Groceries', displayName: 'Station Road Convenience' },
  { pattern: /BALGORES LANE/i, category: 'Groceries', displayName: null },
  { pattern: /ROMFORD MINI/i, category: 'Groceries', displayName: 'Romford Mini Market' },
  { pattern: /GNANAM/i, category: 'Groceries', displayName: 'Gnanam & Son' },
  // Careem Quik is Careem's ~15-minute grocery delivery service — kept in the
  // Groceries block above the Eating Out `CAREEM FOOD` entry so `CAREEM FOOD`
  // still wins on food line-items (first match wins).
  { pattern: /CAREEM QUIK/i, category: 'Groceries', displayName: 'Careem Quik' },

  // ─── Eating Out ─────────────────────────────────────────────────────────────
  { pattern: /DELIVEROO/i, category: 'Eating Out', displayName: 'Deliveroo' },
  { pattern: /JUST EAT/i, category: 'Eating Out', displayName: 'Just Eat' },
  { pattern: /TALABAT/i, category: 'Eating Out', displayName: 'Talabat' },
  { pattern: /ZOMATO/i, category: 'Eating Out', displayName: 'Zomato' },
  { pattern: /MCDONALD/i, category: 'Eating Out', displayName: "McDonald's" },
  { pattern: /KFC/i, category: 'Eating Out', displayName: 'KFC' },
  { pattern: /NANDOS/i, category: 'Eating Out', displayName: "Nando's" },
  { pattern: /PIZZA/i, category: 'Eating Out', displayName: null },
  { pattern: /BURGER/i, category: 'Eating Out', displayName: null },
  { pattern: /WAGAMAMA/i, category: 'Eating Out', displayName: 'Wagamama' },
  { pattern: /SUBWAY/i, category: 'Eating Out', displayName: null },
  { pattern: /DOMINO/i, category: 'Eating Out', displayName: "Domino's" },
  { pattern: /GREGGS/i, category: 'Eating Out', displayName: 'Greggs' },
  { pattern: /STARBUCKS/i, category: 'Eating Out', displayName: 'Starbucks' },
  { pattern: /COSTA COFFEE/i, category: 'Eating Out', displayName: 'Costa Coffee' },
  { pattern: /PRET A MANGER/i, category: 'Eating Out', displayName: 'Pret A Manger' },
  { pattern: /FIVE GUYS/i, category: 'Eating Out', displayName: 'Five Guys' },
  { pattern: /PAPA JOHN/i, category: 'Eating Out', displayName: "Papa John's" },
  { pattern: /CAREEM FOOD/i, category: 'Eating Out', displayName: 'Careem Food' },
  { pattern: /CAREEM DELIVERIES/i, category: 'Eating Out', displayName: 'Careem Deliveries' },
  { pattern: /SLIM CHICKEN/i, category: 'Eating Out', displayName: 'Slim Chickens' },
  { pattern: /TACO BELL/i, category: 'Eating Out', displayName: 'Taco Bell' },
  { pattern: /HOT & TASTY/i, category: 'Eating Out', displayName: 'Hot & Tasty' },
  { pattern: /NAKED CHIPS/i, category: 'Eating Out', displayName: 'Naked Chips' },
  { pattern: /MILLI.?S COFFEE/i, category: 'Eating Out', displayName: "Milli's Coffee" },
  { pattern: /SIZZLIN STEAK/i, category: 'Eating Out', displayName: 'Sizzlin Steak' },
  { pattern: /TRILL JERK/i, category: 'Eating Out', displayName: 'Trill Jerk & Grill' },
  { pattern: /LIGHTHOUSE FISH|LIGHT HOUSE FISH/i, category: 'Eating Out', displayName: 'Lighthouse Fish & Chips' },
  { pattern: /DU.?A FOODS/i, category: 'Eating Out', displayName: "Du'a Foods" },
  { pattern: /HAOZHAN/i, category: 'Eating Out', displayName: 'Haozhan' },
  { pattern: /CAKE BOX/i, category: 'Eating Out', displayName: 'Cake Box' },
  { pattern: /WENZEL/i, category: 'Eating Out', displayName: "Wenzel's" },
  { pattern: /CHICKEN COTTAGE/i, category: 'Eating Out', displayName: 'Chicken Cottage' },
  { pattern: /KRISPY KREME/i, category: 'Eating Out', displayName: 'Krispy Kreme' },
  { pattern: /IVY TREE|IVYTREE/i, category: 'Eating Out', displayName: 'Ivy Tree' },
  { pattern: /BEEFEATER/i, category: 'Eating Out', displayName: 'Beefeater' },
  { pattern: /JOE AND THE JUICE/i, category: 'Eating Out', displayName: 'Joe & The Juice' },
  { pattern: /ROSSI ICES/i, category: 'Eating Out', displayName: 'Rossi Ices' },
  { pattern: /HAMILTON HALL/i, category: 'Eating Out', displayName: 'Hamilton Hall' },
  { pattern: /OPUZ KITCHEN/i, category: 'Eating Out', displayName: 'Opuz Kitchen' },
  { pattern: /MAZING BISTRO/i, category: 'Eating Out', displayName: 'Mazing Bistro Cafe' },
  { pattern: /GOOD HOOD KITCHEN/i, category: 'Eating Out', displayName: 'Good Hood Kitchen' },
  { pattern: /DRILL HOTEL/i, category: 'Eating Out', displayName: 'Drill Hotel' },
  { pattern: /BRICK LANE BAGEL/i, category: 'Eating Out', displayName: 'Brick Lane Bagel' },
  { pattern: /SHUBH SHAGUN/i, category: 'Eating Out', displayName: 'Shubh Shagun' },
  { pattern: /PASTRY/i, category: 'Eating Out', displayName: null },
  { pattern: /CHINATOWN BAKERY/i, category: 'Eating Out', displayName: 'Chinatown Bakery' },
  { pattern: /VENDEASE/i, category: 'Eating Out', displayName: 'Vendease' },
  { pattern: /PASTA RASTA/i, category: 'Eating Out', displayName: 'Pasta Rasta' },
  { pattern: /MISTER SOFTY/i, category: 'Eating Out', displayName: 'Mister Softy' },
  { pattern: /NINO.?S RESTAURANT/i, category: 'Eating Out', displayName: "Nino's Restaurant" },
  { pattern: /COMBAT2COFFEE/i, category: 'Eating Out', displayName: 'Combat2Coffee' },
  { pattern: /BODSON WINE/i, category: 'Eating Out', displayName: null },
  { pattern: /FLIGHT CLUB/i, category: 'Eating Out', displayName: 'Flight Club' },
  { pattern: /HARDEES/i, category: 'Eating Out', displayName: "Hardee's" },
  { pattern: /ARAMARK/i, category: 'Eating Out', displayName: 'Aramark' },
  { pattern: /CWOA ADV/i, category: 'Eating Out', displayName: null },
  { pattern: /QUEENS ARMS/i, category: 'Eating Out', displayName: 'Queens Arms' },
  { pattern: /RESTAURANT ISTANBU/i, category: 'Eating Out', displayName: 'Restaurant Istanbul' },
  { pattern: /DELAWARE NORTH/i, category: 'Eating Out', displayName: 'Delaware North' },
  { pattern: /ZETTLE|MJ S CATERING/i, category: 'Eating Out', displayName: "MJ's Catering" },
  { pattern: /SUMUP \*THE GRILL|THE GRILL\b/i, category: 'Eating Out', displayName: 'The Grill' },
  { pattern: /BALFOUR KINGSTON/i, category: 'Eating Out', displayName: 'Balfour Kingston' },
  { pattern: /TOY MOY/i, category: 'Eating Out', displayName: null },
  { pattern: /PASTURE TRADING/i, category: 'Eating Out', displayName: null },
  { pattern: /MNK\*LA CAFE|LA CAFE/i, category: 'Eating Out', displayName: null },
  { pattern: /KAPOU KAFE/i, category: 'Eating Out', displayName: 'Kapou Kafe (Greece)' },
  { pattern: /CREAMS\b/i, category: 'Eating Out', displayName: 'Creams Cafe' },
  { pattern: /BREW\w*\s*ROMFORD/i, category: 'Eating Out', displayName: 'Brewery Romford' },

  // ─── Transport ──────────────────────────────────────────────────────────────
  { pattern: /\bSHELL\b/i, category: 'Transport', displayName: 'Shell' },
  { pattern: /\bBP\b/i, category: 'Transport', displayName: 'BP' },
  { pattern: /\bJET\b/i, category: 'Transport', displayName: null },
  { pattern: /\bESSO\b/i, category: 'Transport', displayName: 'Esso' },
  { pattern: /TEXACO/i, category: 'Transport', displayName: 'Texaco' },
  { pattern: /\bTHE AA\b/i, category: 'Transport', displayName: 'AA' },
  { pattern: /ALLEN FORD/i, category: 'Transport', displayName: 'Allen Ford' },
  { pattern: /\bRAC\b/i, category: 'Transport', displayName: 'RAC' },
  { pattern: /CONGESTION/i, category: 'Transport', displayName: 'Congestion Charge' },
  { pattern: /PARKING/i, category: 'Transport', displayName: null },
  { pattern: /ULEZ/i, category: 'Transport', displayName: 'ULEZ' },
  { pattern: /DART CHARGE/i, category: 'Transport', displayName: 'Dart Charge' },
  { pattern: /\bTFL\b|OYSTER|TRANSPORT FOR LONDON/i, category: 'Transport', displayName: 'TfL' },
  { pattern: /CAREEM(?! FOOD| DELIVERIES| QUIK)/i, category: 'Transport', displayName: 'Careem' },
  { pattern: /BOLT\.EU/i, category: 'Transport', displayName: 'Bolt' },
  { pattern: /ELITE AUTOCARE/i, category: 'Transport', displayName: 'Elite Autocare' },
  { pattern: /EURO CAR PARKS/i, category: 'Transport', displayName: 'Euro Car Parks' },
  { pattern: /MAYFIELD SERVICE/i, category: 'Transport', displayName: 'Mayfield Service Station' },
  { pattern: /COTTON STREET SERVICE/i, category: 'Transport', displayName: 'Cotton Street Petrol' },
  { pattern: /CANARY WHARF CARPARK/i, category: 'Transport', displayName: 'Canary Wharf Parking' },
  { pattern: /MIPERMIT/i, category: 'Transport', displayName: 'MiPermit Parking' },
  { pattern: /SERVICE STA\w*/i, category: 'Transport', displayName: null },

  // ─── Accommodation (lodging / OTAs — before Travel) ───────────────────────
  { pattern: /AIR\s*BNB|AIRBNB/i, category: 'Accommodation', displayName: 'Airbnb' },
  { pattern: /BOOKING\s*\.?\s*COM/i, category: 'Accommodation', displayName: 'Booking.com' },
  { pattern: /PREMIER INN/i, category: 'Accommodation', displayName: 'Premier Inn' },
  { pattern: /TRAVELODGE/i, category: 'Accommodation', displayName: null },
  { pattern: /HOLIDAY INN/i, category: 'Accommodation', displayName: null },
  { pattern: /CROWNE PLAZA/i, category: 'Accommodation', displayName: null },
  { pattern: /RIXOS/i, category: 'Accommodation', displayName: null },
  { pattern: /WARNER LEISURE/i, category: 'Accommodation', displayName: 'Warner Leisure' },
  { pattern: /PAN PACIFIC/i, category: 'Accommodation', displayName: null },
  { pattern: /EXPEDIA/i, category: 'Accommodation', displayName: 'Expedia' },

  // ─── Travel ─────────────────────────────────────────────────────────────────
  { pattern: /EMIRATES/i, category: 'Travel', displayName: 'Emirates' },
  { pattern: /ENTERPRISE RENT/i, category: 'Travel', displayName: null },
  { pattern: /HERTZ/i, category: 'Travel', displayName: null },
  { pattern: /EASYJET/i, category: 'Travel', displayName: 'easyJet' },
  { pattern: /RYANAIR/i, category: 'Travel', displayName: 'Ryanair' },
  { pattern: /BRITISH AIRWAYS/i, category: 'Travel', displayName: 'British Airways' },
  { pattern: /STARHOLIDAYS/i, category: 'Travel', displayName: null },
  { pattern: /ANYVAN/i, category: 'Travel', displayName: null },
  { pattern: /AE?GEAN\s?AIR|AEGAN\s?AIR/i, category: 'Travel', displayName: 'Aegean Airlines' },
  { pattern: /STANSTED/i, category: 'Travel', displayName: 'Stansted Airport' },
  { pattern: /NOMADESIM/i, category: 'Travel', displayName: 'Nomad eSIM' },
  { pattern: /VIRGIN MONEY TRAVEL/i, category: 'Travel', displayName: 'Virgin Money Travel' },
  { pattern: /PIRAEUS BANK/i, category: 'Travel', displayName: 'Piraeus Bank ATM' },
  { pattern: /AKROTIRI/i, category: 'Travel', displayName: 'Akrotiri (Greece)' },
  { pattern: /IBN BATTUTA/i, category: 'Travel', displayName: 'Ibn Battuta Mall' },
  { pattern: /SOUDA BR/i, category: 'Travel', displayName: 'Souda (Greece)' },
  { pattern: /PETRAKIS/i, category: 'Travel', displayName: 'Petrakis (Greece)' },
  { pattern: /AFOI/i, category: 'Travel', displayName: null },
  { pattern: /BARRIO.*GREECE/i, category: 'Travel', displayName: 'Barrio (Greece)' },
  { pattern: /VIVLIOTHIKI/i, category: 'Travel', displayName: 'Vivliothiki (Greece)' },
  { pattern: /ELLESTIA/i, category: 'Travel', displayName: 'Ellestia Mall (Greece)' },
  { pattern: /LABIRYNTH/i, category: 'Travel', displayName: 'Labirynth (Greece)' },
  { pattern: /STYLIANOS BIKAKIS/i, category: 'Travel', displayName: 'Bikakis (Greece)' },
  { pattern: /NIKOLAKAKIS/i, category: 'Travel', displayName: 'Nikolakakis (Greece)' },
  { pattern: /KAASLAND/i, category: 'Travel', displayName: 'Kaasland (Netherlands)' },
  { pattern: /STACH LOUNGE/i, category: 'Travel', displayName: 'Stach Lounge (Netherlands)' },
  { pattern: /STICHTING PATRONA/i, category: 'Travel', displayName: 'Stichting Patronaat (Netherlands)' },
  { pattern: /SCHIPHOL/i, category: 'Travel', displayName: null },
  { pattern: /MULTI1/i, category: 'Travel', displayName: null },
  { pattern: /SYNKA/i, category: 'Travel', displayName: 'Synka (Greece)' },
  { pattern: /GREECE\b/i, category: 'Travel', displayName: null },
  { pattern: /STN WDF/i, category: 'Travel', displayName: 'Stansted Airport WDF' },
  { pattern: /BIRD NETHERLANDS/i, category: 'Travel', displayName: 'Bird (e-scooter)' },

  // ─── Health & Personal ──────────────────────────────────────────────────────
  { pattern: /DAVID LLOYD/i, category: 'Health & Personal', displayName: 'David Lloyd' },
  { pattern: /\bBOOTS\b/i, category: 'Health & Personal', displayName: 'Boots' },
  { pattern: /PHARMACY/i, category: 'Health & Personal', displayName: null },
  { pattern: /MEDICAL/i, category: 'Health & Personal', displayName: null },
  { pattern: /HOSPITAL/i, category: 'Health & Personal', displayName: null },
  { pattern: /CLINIC/i, category: 'Health & Personal', displayName: null },
  { pattern: /DENTIST/i, category: 'Health & Personal', displayName: null },
  { pattern: /OPTICIAN/i, category: 'Health & Personal', displayName: null },
  { pattern: /SPECSAVERS/i, category: 'Health & Personal', displayName: 'Specsavers' },
  { pattern: /SUPERDRUG/i, category: 'Health & Personal', displayName: 'Superdrug' },
  { pattern: /DENTAL/i, category: 'Health & Personal', displayName: null },
  { pattern: /VETS4PETS|PETS AT HOME/i, category: 'Health & Personal', displayName: 'Pets at Home' },
  { pattern: /PURE GYM/i, category: 'Health & Personal', displayName: 'PureGym' },
  { pattern: /FADES AND BLADES/i, category: 'Health & Personal', displayName: 'Fades & Blades' },
  { pattern: /BARBER/i, category: 'Health & Personal', displayName: null },
  { pattern: /HEALTHPOINT/i, category: 'Health & Personal', displayName: 'Healthpoint' },
  { pattern: /OXLOW CHEMIST/i, category: 'Health & Personal', displayName: 'Oxlow Chemist' },
  { pattern: /BEAUTY WORLD/i, category: 'Health & Personal', displayName: 'Beauty World' },
  { pattern: /COMPANION CARE/i, category: 'Health & Personal', displayName: 'Companion Care Vets' },
  { pattern: /TOM AND JERRY PET/i, category: 'Health & Personal', displayName: 'Tom & Jerry Pets' },
  { pattern: /ORIGIN HEALTH/i, category: 'Health & Personal', displayName: 'Origin Health' },

  // ─── Entertainment ──────────────────────────────────────────────────────────
  { pattern: /NETFLIX/i, category: 'Entertainment', displayName: 'Netflix' },
  { pattern: /SPOTIFY/i, category: 'Entertainment', displayName: 'Spotify' },
  { pattern: /DISNEY/i, category: 'Entertainment', displayName: 'Disney+' },
  { pattern: /APPLE\.COM/i, category: 'Entertainment', displayName: 'Apple' },
  { pattern: /AMAZON PRIME/i, category: 'Entertainment', displayName: 'Amazon Prime' },
  { pattern: /MERLIN/i, category: 'Entertainment', displayName: 'Merlin Entertainments' },
  { pattern: /WARNER\s?BROS/i, category: 'Entertainment', displayName: 'Warner Bros' },
  { pattern: /CINEMA/i, category: 'Entertainment', displayName: null },
  { pattern: /THEATRE/i, category: 'Entertainment', displayName: null },
  { pattern: /TICKETMASTER/i, category: 'Entertainment', displayName: null },
  { pattern: /VUE\b/i, category: 'Entertainment', displayName: null },
  { pattern: /ODEON/i, category: 'Entertainment', displayName: null },
  { pattern: /MAT CODE/i, category: 'Entertainment', displayName: null },
  { pattern: /DAZN/i, category: 'Entertainment', displayName: 'DAZN' },
  { pattern: /YOUTUBE\s?PREMIUM/i, category: 'Entertainment', displayName: 'YouTube Premium' },
  { pattern: /PLAYSTATION/i, category: 'Entertainment', displayName: 'PlayStation' },
  { pattern: /STAR\s?STABLE/i, category: 'Entertainment', displayName: 'Star Stable' },
  { pattern: /PATREON/i, category: 'Entertainment', displayName: 'Patreon' },
  { pattern: /PAYPAL \*X\./i, category: 'Entertainment', displayName: 'X (Twitter)' },
  { pattern: /CHESSINGTON/i, category: 'Entertainment', displayName: 'Chessington' },
  { pattern: /FLIP OUT/i, category: 'Entertainment', displayName: 'Flip Out' },
  { pattern: /NINJA WARRIOR/i, category: 'Entertainment', displayName: 'Ninja Warrior UK' },
  { pattern: /OXYGEN ACTIVEPLAY/i, category: 'Entertainment', displayName: 'Oxygen Activeplay' },
  { pattern: /ROMFORD LEISURE/i, category: 'Entertainment', displayName: 'Romford Leisure Centre' },
  { pattern: /GIDEA PARK L(?:AWN)?/i, category: 'Entertainment', displayName: 'Gidea Park Tennis' },
  { pattern: /KIDSPACE/i, category: 'Entertainment', displayName: 'Kidspace' },
  { pattern: /AXS TICKETS/i, category: 'Entertainment', displayName: 'AXS Tickets' },
  { pattern: /POWERLEAGUE/i, category: 'Entertainment', displayName: 'Powerleague' },
  { pattern: /SEA LIFE/i, category: 'Entertainment', displayName: 'Sea Life' },
  { pattern: /UFS MAGIC/i, category: 'Entertainment', displayName: 'UFS Magic Booking' },
  { pattern: /HORNCHURCH ATHLETIC/i, category: 'Entertainment', displayName: 'Hornchurch Athletic' },
  { pattern: /STEEL YARD/i, category: 'Entertainment', displayName: 'The Steel Yard' },
  { pattern: /BOOM BATTLE|BOOMBAT/i, category: 'Entertainment', displayName: 'Boom Battle Bar' },
  { pattern: /ACTION ROOM/i, category: 'Entertainment', displayName: 'The Action Room' },
  { pattern: /LEGOLAND/i, category: 'Entertainment', displayName: 'Legoland' },
  { pattern: /NOTEMACHINE ATM|ATM\b/i, category: 'Entertainment', displayName: null },
  { pattern: /URLTV/i, category: 'Entertainment', displayName: 'URLTV' },
  { pattern: /AIRTIME HOTEL/i, category: 'Entertainment', displayName: 'Airtime Hotel Movies' },
  { pattern: /ZONE AMUSEMENT/i, category: 'Entertainment', displayName: 'The Zone' },
  { pattern: /JUMP IN/i, category: 'Entertainment', displayName: 'Jump In' },
  { pattern: /MAIDSTONE UNITED/i, category: 'Entertainment', displayName: 'Maidstone United FC' },
  { pattern: /BALLERZ/i, category: 'Entertainment', displayName: 'Ballerz' },
  { pattern: /OJAS PLAY/i, category: 'Entertainment', displayName: 'Ojas Play Cafe' },
  { pattern: /SODEXO/i, category: 'Entertainment', displayName: 'Sodexo' },
  { pattern: /WELCOME BREAK/i, category: 'Entertainment', displayName: 'Welcome Break' },
  { pattern: /OVO ARENA/i, category: 'Entertainment', displayName: 'OVO Arena Wembley' },
  { pattern: /IPSWICH T\w+ FOUNDATION/i, category: 'Entertainment', displayName: 'Ipswich Town Foundation' },
  { pattern: /HAPPY FACE/i, category: 'Entertainment', displayName: 'Happy Face' },
  { pattern: /LLDC BIRMINGHAM/i, category: 'Entertainment', displayName: null },
  { pattern: /SUPERCUPS VENDING/i, category: 'Entertainment', displayName: null },
  { pattern: /SHACK EVENTS/i, category: 'Entertainment', displayName: null },
  { pattern: /WB STUDIO TOUR/i, category: 'Entertainment', displayName: 'WB Studio Tour' },
  { pattern: /TOUCHAR/i, category: 'Entertainment', displayName: null },
  { pattern: /BPHEVENTSLTD/i, category: 'Entertainment', displayName: null },
  { pattern: /ROMFORD[\s-]+ESSEX/i, category: 'Entertainment', displayName: 'Romford Market' },
  { pattern: /ME GROUP INTERNATIONAL/i, category: 'Entertainment', displayName: null },
  { pattern: /BYRON RED\s?STAR(?!.*HAWK)/i, category: 'Entertainment', displayName: 'Byron Red Star' },
  { pattern: /ADVENTURE POINT/i, category: 'Entertainment', displayName: 'Adventure Point' },
  { pattern: /DUOZOULU/i, category: 'Entertainment', displayName: 'Duozoulu' },
  { pattern: /PHOTO MAGIC/i, category: 'Entertainment', displayName: 'Photo Magic' },
  { pattern: /SOCIETY OF OLD/i, category: 'Entertainment', displayName: null },
  { pattern: /RUSSC CLUB/i, category: 'Entertainment', displayName: null },
  { pattern: /NOTTING HILL/i, category: 'Entertainment', displayName: null },

  // ─── Shopping ───────────────────────────────────────────────────────────────
  { pattern: /AMAZON(?! FRESH)(?! PRIME)|AMZNMKTPLACE/i, category: 'Shopping', displayName: 'Amazon' },
  { pattern: /PRIMARK/i, category: 'Shopping', displayName: 'Primark' },
  { pattern: /EBAY/i, category: 'Shopping', displayName: 'eBay' },
  { pattern: /ARGOS/i, category: 'Shopping', displayName: 'Argos' },
  { pattern: /JOHN LEWIS/i, category: 'Shopping', displayName: 'John Lewis' },
  { pattern: /IKEA/i, category: 'Shopping', displayName: 'IKEA' },
  { pattern: /WICKES/i, category: 'Shopping', displayName: 'Wickes' },
  { pattern: /TOPPS TILES/i, category: 'Shopping', displayName: null },
  { pattern: /BUGABOO/i, category: 'Shopping', displayName: null },
  { pattern: /SMYTHS/i, category: 'Shopping', displayName: 'Smyths Toys' },
  { pattern: /NEXT\b/i, category: 'Shopping', displayName: null },
  { pattern: /ZARA/i, category: 'Shopping', displayName: null },
  { pattern: /H&M\b/i, category: 'Shopping', displayName: null },
  { pattern: /TK MAXX/i, category: 'Shopping', displayName: 'TK Maxx' },
  { pattern: /CURRYS/i, category: 'Shopping', displayName: 'Currys' },
  { pattern: /DUNELM/i, category: 'Shopping', displayName: 'Dunelm' },
  { pattern: /AO\.COM/i, category: 'Shopping', displayName: null },
  { pattern: /GEORGE\b/i, category: 'Shopping', displayName: null },
  { pattern: /HUGO BOSS/i, category: 'Shopping', displayName: 'Hugo Boss' },
  { pattern: /JD SPORTS/i, category: 'Shopping', displayName: 'JD Sports' },
  { pattern: /SPORTS\s?DIRECT/i, category: 'Shopping', displayName: 'Sports Direct' },
  { pattern: /MOL\*PROKIT|PROKIT/i, category: 'Shopping', displayName: 'Prokit UK' },
  { pattern: /B&Q|B & Q/i, category: 'Shopping', displayName: 'B&Q' },
  { pattern: /SCREWFIX/i, category: 'Shopping', displayName: 'Screwfix' },
  { pattern: /POUNDLAND/i, category: 'Shopping', displayName: 'Poundland' },
  { pattern: /WHSMITH/i, category: 'Shopping', displayName: 'WHSmith' },
  { pattern: /SCHUH/i, category: 'Shopping', displayName: 'Schuh' },
  { pattern: /\bCLARKS\b/i, category: 'Shopping', displayName: 'Clarks' },
  { pattern: /CARD FACTORY/i, category: 'Shopping', displayName: 'Card Factory' },
  { pattern: /THE RANGE\b/i, category: 'Shopping', displayName: 'The Range' },
  { pattern: /ONEBEYOND/i, category: 'Shopping', displayName: 'OneBeyond' },
  { pattern: /FOOT LOCKER/i, category: 'Shopping', displayName: 'Foot Locker' },
  { pattern: /RIVER ISLAND/i, category: 'Shopping', displayName: 'River Island' },
  { pattern: /LACOSTE/i, category: 'Shopping', displayName: 'Lacoste' },
  { pattern: /TIMBERLAND/i, category: 'Shopping', displayName: 'Timberland' },
  { pattern: /HVP RETAIL/i, category: 'Shopping', displayName: 'HVP Retail' },
  { pattern: /TROPH/i, category: 'Shopping', displayName: 'Trophy Store' },
  { pattern: /POST OFFICE/i, category: 'Shopping', displayName: 'Post Office' },
  { pattern: /SPORTSWEAR MARKET/i, category: 'Shopping', displayName: 'Sportswear Market' },
  { pattern: /LIBERTY SHOPP/i, category: 'Shopping', displayName: 'Liberty Shopping Centre' },
  { pattern: /THE MEADOWS RETAIL/i, category: 'Shopping', displayName: null },
  { pattern: /PLATFORM 9/i, category: 'Shopping', displayName: 'Platform 9 3/4 Shop' },
  { pattern: /LAKESIDE\b/i, category: 'Shopping', displayName: null },
  { pattern: /FATSOMA/i, category: 'Shopping', displayName: 'Fatsoma' },
  { pattern: /BLACK OUD/i, category: 'Shopping', displayName: 'Black Oud Perfumes' },
  { pattern: /POMVOM/i, category: 'Shopping', displayName: 'Pomvom UK' },
  { pattern: /MOTHER GROUP/i, category: 'Shopping', displayName: 'Mother Group' },
  { pattern: /UK031 ROMFORD|^Romford$|ROMFORD ON \d{2}/i, category: 'Shopping', displayName: null },

  // ─── Business ───────────────────────────────────────────────────────────────
  { pattern: /\bAWS\b/i, category: 'Business', displayName: 'AWS' },
  { pattern: /GITHUB/i, category: 'Business', displayName: 'GitHub' },
  { pattern: /GODADDY/i, category: 'Business', displayName: 'GoDaddy' },
  { pattern: /SWELL/i, category: 'Business', displayName: 'Swell' },
  { pattern: /MCE ADVISO/i, category: 'Business', displayName: 'MCE Advisory' },
  { pattern: /PROTON/i, category: 'Business', displayName: 'Proton' },
  { pattern: /OPENAI|CHATGPT/i, category: 'Business', displayName: 'OpenAI' },
  { pattern: /CLOUDFLARE/i, category: 'Business', displayName: 'Cloudflare' },
  { pattern: /DIGITALOCEAN|DIGITAL OCEAN/i, category: 'Business', displayName: 'DigitalOcean' },
  { pattern: /VERCEL/i, category: 'Business', displayName: null },
  { pattern: /NETLIFY/i, category: 'Business', displayName: null },
  { pattern: /CURSOR/i, category: 'Business', displayName: 'Cursor' },
  { pattern: /ANTHROPIC/i, category: 'Business', displayName: 'Anthropic' },
  { pattern: /ADOBE/i, category: 'Business', displayName: 'Adobe' },
  { pattern: /MICROSOFT/i, category: 'Business', displayName: 'Microsoft' },
  { pattern: /GOOGLE CLOUD/i, category: 'Business', displayName: 'Google Cloud' },
  { pattern: /PLURALSIGHT/i, category: 'Business', displayName: 'Pluralsight' },
  { pattern: /FIVERR/i, category: 'Business', displayName: 'Fiverr' },
  { pattern: /SMARTERASP/i, category: 'Business', displayName: 'SmarterASP' },
  { pattern: /LOVABLE/i, category: 'Business', displayName: 'Lovable' },
  { pattern: /SHOPIFY/i, category: 'Business', displayName: 'Shopify' },
  { pattern: /COMPANIESHOUSE|COMPANIES\s?HOUSE/i, category: 'Business', displayName: 'Companies House' },
  { pattern: /VEO TECHNOLOGIES/i, category: 'Business', displayName: 'Veo Technologies' },
  { pattern: /TWILIO/i, category: 'Business', displayName: 'Twilio' },
  { pattern: /PLAN FEE/i, category: 'Business', displayName: 'Plan Fee' },
  { pattern: /CHARGES COMMISSION|CHARGES\*.*TFR/i, category: 'Business', displayName: 'Bank Charges' },
  { pattern: /UNPAID TRANSAC FEE/i, category: 'Business', displayName: 'Unpaid Transaction Fee' },
  { pattern: /\d{2}(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC) A(?:\/| )C/i, category: 'Other', displayName: 'NatWest Account Fee' },
  { pattern: /INTEREST CHARGED/i, category: 'Business', displayName: 'Interest Charged' },
  { pattern: /PAYPAL \*STEAM/i, category: 'Business', displayName: 'Steam Games' },
  { pattern: /PAYPAL \*SEGPAY/i, category: 'Business', displayName: 'Segpay Subscription' },
  { pattern: /PAYPAL \*LONDONLOUIS/i, category: 'Business', displayName: null },
  { pattern: /PAYPAL \*LAZZDA/i, category: 'Business', displayName: null },
  { pattern: /BYRON REDSTAR HAWK/i, category: 'Business', displayName: 'Byron Redstar Sponsorship' },
  { pattern: /IGB HOLDINGS|SUMUP \*IGB/i, category: 'Business', displayName: null },

  // ─── Property ───────────────────────────────────────────────────────────────
  { pattern: /EDU-LETTIN/i, category: 'Property', displayName: 'Edu-Lettings' },
  { pattern: /LETTING/i, category: 'Property', displayName: null },
  { pattern: /ESTATE AGENT/i, category: 'Property', displayName: null },
  { pattern: /J SMITH WOOD/i, category: 'Property', displayName: 'J Smith Woodwork' },
  { pattern: /TJ LANDSCAP/i, category: 'Property', displayName: 'TJ Landscaping' },
  { pattern: /FLOOR REPAIR/i, category: 'Property', displayName: null },
  { pattern: /STONESHAW/i, category: 'Property', displayName: null },
  { pattern: /PROSPECT HOLDING/i, category: 'Property', displayName: 'Prospect Holdings' },
  { pattern: /SHURGARD|STORAGE/i, category: 'Property', displayName: 'Storage' },
  { pattern: /ALBO PLUMBING/i, category: 'Property', displayName: null },
  { pattern: /RM2 FLOORING/i, category: 'Property', displayName: null },
  { pattern: /GLASSMASTER/i, category: 'Property', displayName: null },
  { pattern: /FENSOME ELECTRICAL/i, category: 'Property', displayName: null },
  { pattern: /PLUMB/i, category: 'Property', displayName: null },
  { pattern: /DISPUTE SERVICE/i, category: 'Property', displayName: 'The Dispute Service' },
  { pattern: /JS-LAW/i, category: 'Property', displayName: 'JS Law' },
  { pattern: /CLEANSATION/i, category: 'Property', displayName: 'Cleansation' },
];
